/**
 * OTR Earthmover Tyre, Knowledge Portal ASK endpoint (Supabase backend).
 *
 * POST { q: string }
 *
 * Pipeline (mirrors worker/api/ask.js, same response contract):
 *   Pricing guard, commercial questions decline and escalate to David,
 *     checked BEFORE Track A so "how much does a 40.00R57 cost?" never
 *     dumps that size's spec records.
 *   Track A, numeric spec questions (a size, or a TRA code + value word) are
 *     answered by exact lookup in kb_specs (verified rows only, rendered as a
 *     spec table) or ABSTAIN. They never reach retrieval or a language model.
 *     Comparative/recommendation questions ("26.5R25 alternatives to
 *     Bridgestone") are excluded, they want a discussion, not a spec table.
 *   Track B, embed the question (gte-small, built into the edge runtime),
 *     hybrid match over kb_chunks (vector + keyword), then:
 *       • extractive mode (default, no key needed): verbatim passages + citations
 *       • generative mode (ANTHROPIC_API_KEY secret set): plain-language summary
 *         + up to 3 RELATED follow-up questions via the sentinel format
 *   Fallback, nothing relevant: labelled general guidance via Claude if a key
 *     is set, else an honest "not in my sources".
 *
 * RESPONSE CONTRACT (guardrail, see ../../ask.html renderApiAnswer/renderAnswer):
 *   Every path below returns the same four fields, always populated, so the
 *   front end can render Question / Answer / Opinion / Sources in a fixed
 *   order with no branch-specific layout:
 *     - lede:       one-sentence headline answer
 *     - answer:     HTML, the factual/descriptive content (table, prose, or
 *                   verbatim excerpts). Never a recommendation or call to action.
 *     - suggestion: HTML, the actionable next step: what to do, what to check,
 *                   who to call, or a caveat. NEVER blank, every path below
 *                   sets an explicit suggestion, even a generic one. Rendered
 *                   under the "/ OPINION" label on the front end.
 *     - sources:    array (possibly empty) of {num, text, url}
 *   `body` is also set (mirrors `answer`) for older consumers that read the
 *   pre-guardrail contract (e.g. the Cloudflare Pages proxy fallback path).
 *
 * Displayed verbatim excerpts are prose-only in generative mode (an empty
 * quote section beats table debris; the cited answer + source links stand on
 * their own). Extractive mode falls back to raw matches because there the
 * excerpts ARE the answer. Retrieval/LLM context are never filtered.
 */
import { createClient } from "npm:@supabase/supabase-js@2";

const TOP_K = 8;
const CONFIDENT_TOP = 0.80;
const EXCERPT_MIN = 0.78;
const CLAUDE_MODEL = "claude-sonnet-5";
const CALL_DAVID = '<strong><a href="tel:+61419358439">0419 358 439</a></strong>';

const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
// deno-lint-ignore no-explicit-any
const ai = new (globalThis as any).Supabase.ai.Session("gte-small");

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const DISCLAIMER = `\n\n---\n*This answer is AI-generated by the OTR Earthmover Tyre Knowledge Portal from publicly available manufacturer databooks, Australian Standards material, and 50 years of independent OTR trading experience. It is the opinion of an independent trader, offered as general technical reference, not engineering advice, and not a recommendation to act on without checking. For a specific machine, application, or fleet decision, confirm against current OEM specifications and qualified inspection.*`;

const SOURCE_LINKS: [RegExp, string][] = [
  [/bridgestone[-\s]*(otr|earthmover)/i, "https://commercial.bridgestone.com/content/dam/bcs-sites/bridgestone-ex/products/Databooks/Archive/Bridgestone-OTR-Databook-2018-09-06-2018.pdf"],
  [/michelin[-\s]*(otr|earthmover)/i, "https://www.michelinb2b.com/wps/b2bcontent/OHT/EMDataBook_Global_E.pdf"],
  [/goodyear[-\s]*otr/i, "https://www.goodyearotr.com/resources/engineering-data"],
  [/bkt[-\s]*(industrial|otr)/i, "https://otrtires.com/wp-content/uploads/24-BKT-Industrial-catalogue.pdf"],
  [/yokohama/i, "https://www.y-yokohama.com/global/product/tire/pdf/tires/catalogue/OR_HB02.pdf"],
  [/tire[-\s]*and[-\s]*rim|\btra\b/i, "https://www.us-tra.org/publications/"],
  [/as[-\s]?4457/i, "https://store.standards.org.au/product/as-4457-2-2008"],
  [/reference\.html/i, "https://otrearthmovertyres.com/reference.html"],
  [/tyres\.html/i, "https://otrearthmovertyres.com/tyres.html"],
  [/jewell/i, "https://jewelltyres.com.au"],
];
const SOURCE_FALLBACK = "https://otrearthmovertyres.com/resources.html";

function sourceUrl(s: string, page?: number | null): string {
  let url = SOURCE_FALLBACK;
  for (const [re, u] of SOURCE_LINKS) { if (re.test(s)) { url = u; break; } }
  if (page && /\.pdf$/i.test(url)) url += `#page=${page}`;
  return url;
}

function esc(s: string): string {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

// Is a retrieved chunk readable prose, or table/header debris? Display-only.
function isProseExcerpt(t: string): boolean {
  const words = t.trim().split(/\s+/);
  if (words.length < 12) return false;
  const digits = (t.match(/\d/g) || []).length;
  if (digits / t.length > 0.22) return false;
  const norm = words.map((w) => w.toLowerCase().replace(/[^a-z0-9./-]/g, ""));
  if (new Set(norm).size / words.length < 0.5) return false;
  const fn = norm.filter((w) => /^(the|and|of|to|a|is|are|for|with|in|on|be|or|it|that|as|at|by|this|from|not|when|should)$/.test(w)).length;
  if (fn / words.length < 0.06) return false;
  const lower = words.filter((w) => /^[a-z]/.test(w)).length;
  return lower / words.length >= 0.5;
}

// A response with `answer` set is complete per the guardrail contract; `body`
// mirrors `answer` for pre-guardrail consumers. Every return path below MUST
// pass a non-empty `suggestion`.
function contract(parts: {
  lede: string; answer: string; suggestion: string;
  sources?: unknown[]; excerpts?: unknown[]; citations?: unknown[]; related?: string[];
  clarify?: string;
  escalation: boolean; abstained?: boolean; mode?: string;
}) {
  return {
    lede: parts.lede,
    answer: parts.answer,
    body: parts.answer,
    suggestion: parts.suggestion,
    sources: parts.sources ?? [],
    excerpts: parts.excerpts ?? [],
    citations: parts.citations ?? [],
    related: parts.related ?? [],
    clarify: parts.clarify ?? "",
    escalation: parts.escalation,
    abstained: parts.abstained ?? false,
    mode: parts.mode,
    disclaimer: DISCLAIMER,
  };
}

// --- Pricing guard: commercial questions are David's, not the portal's.
const PRICING_RE = /\b(price|prices|pricing|cost|costs|quote|quotation)\b|\bhow much (is|are|do|does|for|would|will)\b|\$|\bAUD\b/i;

function pricingAnswer() {
  return contract({
    lede: "We don't do pricing here. That's a phone call.",
    answer: "<p>OTR tyre prices move with brand, condition (new, unused surplus, secondhand), quantity, location and freight. Anything we published today would be wrong by next week.</p>",
    suggestion: `<p>For a real number on the tyre you're after, call David Jewell direct on ${CALL_DAVID}, or start a buy enquiry at <a href="https://jewelltyres.com.au/buy-tyres.html">jewelltyres.com.au</a>. 50 years of trading, straight answers.</p>`,
    escalation: true,
  });
}

// --- Track A: numeric specifications are served by exact lookup, never an LLM.
const SIZE_RE = /\b(\d{1,2}\.\d{2}R\d{2}|\d{2}\/\d{2}R\d{2}|\d{2}\.\dR\d{2}|\d{1,2}\.\d{2}-\d{2})\b/;
const TRA_RE = /\b([ELG]-\d[A-Z]?)\b/;
const VALUE_HINT = /\b(rim|inflation|pressure|kpa|psi|load|tkph|tmph|section width|overall diameter|width|diameter)\b/i;
// Comparative / recommendation intent means a discussion, not a spec table,
// "26.5R25 alternatives to Bridgestone" wants brands compared, not one brand's rows.
const COMPARE_RE = /\balternativ\w*|\bcompar\w*|\bversus\b|\bvs\.?\s|\binstead of\b|\bequivalent\w*|\bbetter than\b|\bbest\b|\boptions?\b|\brecommend(?!ed (rim|inflation|pressure|load))\w*/i;

function isSpecLookup(q: string): boolean {
  if (COMPARE_RE.test(q)) return false;
  return SIZE_RE.test(q) || (TRA_RE.test(q) && VALUE_HINT.test(q));
}

interface SpecRow {
  brand: string; pattern: string | null; tyre_size: string; tra_code: string | null;
  star_rating: string | null; load_rating: string | null; rim: string | null;
  inflation_kpa: number | null; tkph: number | null; source: string | null;
  page: number | null; verified_at: string | null;
}

const SPEC_TH = 'style="text-align:left;padding:0.45rem 1rem 0.45rem 0;font-weight:400;color:var(--otr-steel-light);white-space:nowrap;border-bottom:1px solid var(--otr-rule);width:40%;"';
const SPEC_TD = 'style="text-align:left;padding:0.45rem 0;color:var(--otr-bone);font-family:var(--otr-mono);border-bottom:1px solid var(--otr-rule);"';

// Query-hinted spec fields: if the question names one and no matched row holds
// it, say so in the suggestion rather than letting the column silently vanish.
const FIELD_HINTS: [RegExp, keyof SpecRow, string][] = [
  [/inflation|pressure|kpa|psi/i, "inflation_kpa", "inflation pressure"],
  [/tkph|tmph/i, "tkph", "TKPH"],
  [/load/i, "load_rating", "load rating"],
];

async function numericAnswer(query: string) {
  const size = (query.match(SIZE_RE) || [])[0];
  const tra = (query.match(TRA_RE) || [])[0];
  let rows: SpecRow[] = [];
  if (size) {
    const { data } = await supabase.from("kb_specs").select("*")
      .ilike("tyre_size", size.replace(/\s+/g, "")).not("verified_at", "is", null).limit(10);
    rows = (data as SpecRow[]) ?? [];
  }
  if (!rows.length && tra) {
    const { data } = await supabase.from("kb_specs").select("*")
      .ilike("tra_code", tra).not("verified_at", "is", null).limit(10);
    rows = (data as SpecRow[]) ?? [];
  }
  if (rows.length) {
    const FIELDS: [keyof SpecRow, string][] = [["tra_code", "TRA code"], ["star_rating", "star rating"],
      ["load_rating", "load rating"], ["rim", "recommended rim"], ["inflation_kpa", "inflation pressure (kPa)"], ["tkph", "TKPH"]];
    const sources: unknown[] = [];
    let answer = "";
    rows.forEach((r, i) => {
      const head = `${r.tyre_size}${r.tra_code ? " " + r.tra_code : ""}, ${r.brand}${r.pattern ? " " + r.pattern : ""}`;
      const trs = FIELDS.filter(([k]) => r[k] !== null && r[k] !== undefined && r[k] !== "")
        .map(([k, label]) => `<tr><th ${SPEC_TH}>${label}</th><td ${SPEC_TD}>${esc(String(r[k]))}</td></tr>`).join("");
      answer += `<p style="margin:1.25rem 0 0.5rem;"><strong>${esc(head)}</strong></p>`
        + `<div style="overflow-x:auto;"><table style="width:100%;border-collapse:collapse;font-size:0.92rem;">${trs}</table></div>`;
      sources.push({ num: String(i + 1).padStart(2, "0"),
        text: `${r.source ?? r.brand + " databook"}${r.page ? `, p.${r.page}` : ""}`,
        url: sourceUrl(r.source ?? r.brand, r.page) });
    });
    // Values the question asked for that the signed-off set doesn't hold.
    const missing = FIELD_HINTS
      .filter(([re, k]) => re.test(query) && rows.every((r) => r[k] === null || r[k] === undefined || r[k] === ""))
      .map(([, , label]) => label);
    let suggestion = '<p>Transcribed verbatim from the cited databook edition, not generated. Editions change and transcription errors happen, so confirm against the current manufacturer specification before you act.</p>';
    if (missing.length) {
      suggestion += `<p>The signed-off set doesn't hold ${missing.join(" or ")} for this size. Confirm it against the current manufacturer databook or call David Jewell on ${CALL_DAVID}.</p>`;
    }
    const what = rows[0]?.tyre_size || rows[0]?.tra_code || "that spec";
    const lede = `${rows.length === 1 ? "One signed-off record" : rows.length + " signed-off records"} for ${what}.`;
    return contract({ lede, answer, suggestion, sources, escalation: false, abstained: false });
  }
  return contract({
    lede: "That figure is not in the verified, signed-off dataset, so it is not reproduced here.",
    answer: '<p>Specification values (load, rim, inflation, TKPH) are served only from manufacturer databooks that have been dual-pass verified and signed off, not generated. This value is not in that set. The portal does not estimate specification values.</p>',
    suggestion: `<p>Confirm against the current manufacturer specification, or call David Jewell direct on ${CALL_DAVID}.</p>`,
    escalation: true, abstained: true,
  });
}

interface Match { id: string; source: string; section: string; page: number | null; content: string; similarity: number }

// Some models return a leading non-text block (e.g. thinking) before the
// actual answer, so content[0] is not reliably the text block, find the
// first block whose type is "text" instead of assuming position 0.
function firstText(content: unknown): string {
  if (!Array.isArray(content)) return "";
  const block = content.find((b: { type?: string }) => b?.type === "text");
  return (block as { text?: string } | undefined)?.text ?? "";
}

// Deterministic backstop for the prompt's no-dash rule: models drift back to
// em dashes under long context, and one dash undoes the whole human-voice
// effort. Em dashes become commas; en dashes too, except between digits
// (numeric ranges like 68-153 keep their separator, normalised to a hyphen).
// If generation stopped at the token cap, a section can end mid-sentence.
// Trim back to the last complete sentence and close any tags left open so the
// page never renders a dangling clause or broken HTML.
function trimToSentence(html: string): string {
  const t = (html || "").replace(/\s+$/, "");
  if (!t) return t;
  if (/[.!?]["')\]]*\s*(<\/[a-z]+>\s*)*$/i.test(t)) return t;
  let idx = -1;
  const re = /[.!?](?=["')\]]*(\s|<|$))/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(t))) idx = m.index;
  return idx >= 0 ? t.slice(0, idx + 1) : t;
}
function closeOpenTags(html: string): string {
  let out = html;
  for (const tag of ["strong", "em", "sup", "li", "ul", "p"]) {
    const opens = (out.match(new RegExp(`<${tag}[\\s>]`, "g")) || []).length;
    const closes = (out.match(new RegExp(`</${tag}>`, "g")) || []).length;
    for (let i = closes; i < opens; i++) out += `</${tag}>`;
  }
  return out;
}
function deDash(s: string): string {
  return s
    .replace(/\s*—\s*/g, ", ")
    .replace(/(\d)\s*–\s*(\d)/g, "$1-$2")
    .replace(/\s*–\s*/g, ", ")
    .replace(/,\s*,/g, ", ")
    .replace(/([.!?])\s*,\s*/g, "$1 ");
}

async function generalAnswer(query: string, userContent?: string) {
  const apiKey = Deno.env.get("ANTHROPIC_API_KEY");
  if (!apiKey) return null;
  const GENERAL_SYSTEM = `You are the Knowledge Portal for OTR Earthmover Tyre, maintained by Jewell Tyres, independent OTR tyre specialists since 1975. The verified corpus did NOT contain material for this question, so you are answering from general off-the-road tyre knowledge.

VOICE, answer like an independent OTR tyre trader with fifty years in the trade: plain-spoken, practical, careful and commercially honest. Australian spelling (tyre, fitment, programme, behaviour). Independent of every manufacturer. Talk the way David talks on the phone: short, plain sentences, no filler, straight answers first. Honest about uncertainty, limits and assumptions. Prefer phrases like "the straight answer is", "what we'd run", "the constraint is", "confirm before acting". No hype, no generic AI phrasing, no corporate marketing language.

PUNCTUATION, hard rule: NEVER use an em dash or en dash in your prose. Use a comma, a full stop, or brackets instead. Hyphens in compound words and numeric ranges are fine.

SCANNABILITY, paragraphs of one to three short sentences. Wrap load-bearing terms and values in <strong>. Three or more parallel items go in a <ul> bullet list, one short line each.

RULES:
- Start with the direct answer, then the practical reason. 1-2 short paragraphs.
- This answer is NOT from the verified sources, do not present any claim as sourced or quoted. Say "general reference only" where needed.
- NEVER state a specific numeric specification: load rating/index, rim width, inflation pressure, section width, overall diameter, or a TKPH/TMPH figure. If one is needed, say it must be read from the manufacturer databook and do not estimate it.
- Do not declare a single brand/model "the best", frame options and trade-offs by application. Never present a tyre view as engineering advice; own it as opinion. Never guarantee safety, performance, legality, availability or price.
- If the answer affects fitment, mixing, pressure, TKPH, repair, scrap, compliance or machine operation: end with a short verification note, confirm against current manufacturer data, OEM limits, AS4457:2019 and a competent tyre engineer/fitter.
- Mention Jewell Tyres only if the user asks about buying, selling, sourcing, availability, alternatives or trade options, factual, not a sales pitch. For pricing, contracts, or fleet-specific decisions, decline and point to David Jewell.
- Return only HTML paragraphs (<p>…</p>). No headings, no markdown, no emoji.`;
  try {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: { "Content-Type": "application/json", "x-api-key": apiKey, "anthropic-version": "2023-06-01" },
      body: JSON.stringify({ model: CLAUDE_MODEL, max_tokens: 800, system: GENERAL_SYSTEM, messages: [{ role: "user", content: userContent || query }] }),
    });
    if (!res.ok) return null;
    const j = await res.json();
    const text: string = firstText(j.content);
    if (!text.trim()) return null;
    const bodyHtml = deDash(/<p[\s>]/i.test(text) ? text
      : "<p>" + esc(text).trim().replace(/\n{2,}/g, "</p><p>").replace(/\n/g, " ") + "</p>");
    return contract({
      lede: "Not in the verified sources. Here's our general read on it.",
      answer: bodyHtml,
      suggestion: "<p>Not in our verified sources, so this is general opinion, not a sourced spec and not advice. Check it against the manufacturer databook, or call David.</p>",
      escalation: shouldEscalate(query), mode: "general",
    });
  } catch { return null; }
}

function shouldEscalate(query: string): boolean {
  return [
    /price|cost|quote|how much|\$/i,
    /which brand|best (tyre|brand|option)/i,
    /contract|terms|commercial|fleet/i,
    /buy.*now|need.*urgent/i,
    // Safety-critical topics are always worth a phone call.
    /\bmix(ing)?\b|\bweld\w*|\bfire\b|\bexplos\w*|\bburst\b|\bzipper\b|\bderat\w*|\brepair\w*|\bdamag\w*|\bfail(ure|ing|ed)?\b|\binjur\w*|\bkill\w*|\bsafe(ty)?\b|\binflat\w* (danger|risk|safe)/i,
  ].some((rx) => rx.test(query));
}

function noAnswer(query: string) {
  return {
    q: esc(query),
    ...contract({
      lede: "We don't have a solid answer for that in what we've got.",
      answer: "<p>Nothing in the Knowledge Portal comes close enough to that question. Could be it sits outside this corpus (pricing, commercial terms, real-time supply), could just be how it's phrased.</p>",
      suggestion: `<p>Try narrowing it down, machine, size, or TRA code, or call David Jewell direct on ${CALL_DAVID}.</p>`,
      escalation: true,
    }),
  };
}

function logQuery(question: string, mode: string, abstained: boolean, topSource: string | null) {
  supabase.from("kb_query_log").insert({ question, mode, abstained, top_source: topSource }).then(() => {});
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });
  if (req.method !== "POST") return json({ error: "Method Not Allowed" }, 405);

  try {
    const body = await req.json().catch(() => ({}));
    const query = (body.q || "").trim();
    if (!query) return json({ error: "Query required", disclaimer: DISCLAIMER }, 400);
    if (query.length > 500) return json({ error: "Query too long (500 char max)", disclaimer: DISCLAIMER }, 400);
    // Follow-up support: the page may send the previous exchange as reference.
    // Only the question and the answer's headline travel, both length-capped.
    const priorIn = body && typeof body.prior === "object" ? body.prior : null;
    const prior = priorIn && priorIn.q ? {
      q: String(priorIn.q).slice(0, 300),
      lede: String(priorIn.lede || "").replace(/<[^>]+>/g, "").slice(0, 300),
    } : null;
    const userContent = prior
      ? `Earlier question in this conversation: "${prior.q}"\nThe headline of our answer was: "${prior.lede}"\nIf the earlier exchange is unrelated to the new question, ignore it.\n\nNew question: ${query}`
      : query;

    if (PRICING_RE.test(query)) {
      logQuery(query, "pricing", true, null);
      return json({ q: esc(query), ...pricingAnswer() });
    }

    if (isSpecLookup(query)) {
      const ans = await numericAnswer(query);
      logQuery(query, "spec", ans.abstained, null);
      return json({ q: esc(query), ...ans });
    }

    // Track B, retrieve
    // Answer cache: a repeated identical question (e.g. a page refresh
    // replaying ?q=) serves the stored answer, byte-identical and instant,
    // instead of regenerating a differently-worded one. 7 day TTL.
    const cacheKey = query.toLowerCase().replace(/\s+/g, " ").trim() + "||" +
      (prior ? prior.q.toLowerCase().replace(/\s+/g, " ").trim() : "");
    const { data: cachedRow } = await supabase.from("kb_answer_cache")
      .select("response")
      .eq("key", cacheKey)
      .gte("created_at", new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString())
      .maybeSingle();
    if (cachedRow?.response) {
      logQuery(query, "cached", false, null);
      return json(cachedRow.response);
    }
    const cacheStore = (payload: unknown) => {
      supabase.from("kb_answer_cache")
        .upsert({ key: cacheKey, question: query, response: payload, created_at: new Date().toISOString() })
        .then(() => {});
    };
    const searchText = prior ? `${prior.q} ${query}` : query;
    const embedding = await ai.run(searchText, { mean_pool: true, normalize: true });
    const { data: matches, error: rpcError } = await supabase.rpc("kb_match_chunks", {
      query_embedding: JSON.stringify(Array.from(embedding as number[])),
      query_text: searchText,
      match_count: TOP_K,
    });
    if (rpcError) throw new Error(`kb_match_chunks failed: ${rpcError.message}`);

    const all = (matches ?? []) as Match[];
    if (!all.length || all[0].similarity < CONFIDENT_TOP) {
      const g = await generalAnswer(query, userContent);
      logQuery(query, g ? "general" : "none", true, null);
      if (g) {
        const payload = { q: esc(query), ...g };
        cacheStore(payload);
        return json(payload);
      }
      return json(noAnswer(query));
    }

    const valid = all.filter((m) => m.similarity >= EXCERPT_MIN).slice(0, TOP_K);
    const sources = valid.map((m, i) => ({
      num: String(i + 1).padStart(2, "0"),
      text: m.source + (m.section && m.section !== "General" ? `, ${m.section}` : "") + (m.page ? `, p.${m.page}` : ""),
      url: sourceUrl(m.source, m.page),
    }));
    // Prose-only excerpts in generative mode; raw fallback only in extractive.
    const mkExcerpts = (arr: Match[]) => arr.slice(0, 4).map((m, i) => ({
      num: String(i + 1).padStart(2, "0"),
      source: m.source + (m.page ? `, p.${m.page}` : ""),
      text: m.content.trim().slice(0, 300),
      url: sourceUrl(m.source, m.page),
    }));
    let excerpts = mkExcerpts(valid.filter((m) => isProseExcerpt(m.content || "")));

    // Verified spec records for any tyre size named in the query or retrieved
    // context. These are transcribed, dual-pass signed-off databook values, so
    // unlike generated numbers the model is allowed to quote them, with a
    // citation. Max 4 sizes, max 8 rows, deduped.
    const sizeReG = new RegExp(SIZE_RE.source, "g");
    const namedSizes = [...new Set(
      [...((query + " " + valid.map((m) => m.content).join(" ")).matchAll(sizeReG))].map((m) => m[0])
    )].slice(0, 4);
    let specRows: SpecRow[] = [];
    for (const s of namedSizes) {
      const { data } = await supabase.from("kb_specs").select("*")
        .ilike("tyre_size", `%${s}%`).not("verified_at", "is", null).limit(6);
      for (const r of (data as SpecRow[]) ?? []) {
        if (!specRows.some((x) => x.brand === r.brand && x.pattern === r.pattern && x.tyre_size === r.tyre_size)) {
          specRows.push(r);
        }
      }
    }
    specRows = specRows.slice(0, 8);
    let specBlock = "";
    const specSources: { num: string; text: string; url: string }[] = [];
    if (specRows.length) {
      const lines = specRows.map((r, i) => {
        const n = valid.length + i + 1;
        specSources.push({
          num: String(n).padStart(2, "0"),
          text: `${r.source ?? r.brand + " databook"}${r.page ? `, p.${r.page}` : ""} (verified spec record)`,
          url: sourceUrl(r.source ?? r.brand, r.page),
        });
        const bits = [
          r.tra_code ? `TRA ${r.tra_code}` : "",
          r.star_rating ? `star rating ${r.star_rating}` : "",
          r.load_rating ? `load rating ${r.load_rating}` : "",
          r.rim ? `rim ${r.rim}` : "",
          r.inflation_kpa != null ? `inflation ${r.inflation_kpa} kPa` : "",
          r.tkph != null ? `TKPH ${r.tkph}` : "",
        ].filter(Boolean).join(", ");
        return `[Source ${n}] ${r.brand}${r.pattern ? " " + r.pattern : ""} ${r.tyre_size}${bits ? ", " + bits : ""}`;
      });
      specBlock = "\n\n## VERIFIED SPEC RECORDS\nTranscribed verbatim from the cited manufacturer databooks and signed off. Unlike other numbers, these figures MAY be quoted exactly, each with its [n] citation. Do not extrapolate beyond them.\n\n" + lines.join("\n");
    }

    const apiKey = Deno.env.get("ANTHROPIC_API_KEY");
    const extractive = () => {
      if (!excerpts.length) excerpts = mkExcerpts(valid);
      const answer = excerpts.map((x) => `<p><strong>[${x.num}]</strong> ${esc(x.text)}…</p>`).join("");
      return json({
        q: esc(query),
        ...contract({
          lede: "Straight from our reference library. The passages most relevant to your question:",
          answer,
          suggestion: '<p>These are raw retrieved passages, not a synthesised answer. Read them in context, or ask a follow-up question to narrow it down.</p>',
          sources, excerpts, citations: excerpts.map((x) => x.num),
          escalation: false,
        }),
      });
    };
    if (!apiKey) {
      logQuery(query, "extractive", false, valid[0]?.source ?? null);
      return extractive();
    }

    // Generative mode: summary composed strictly from the retrieved context.
    const context = valid.map((m, i) =>
      `[Source ${i + 1}: ${m.source}${m.section ? `, ${m.section}` : ""}${m.page ? `, p.${m.page}` : ""}]\n${m.content}`
    ).join("\n\n---\n\n");
    const SYSTEM = `You are the Knowledge Portal for OTR Earthmover Tyre, an independent technical reference site maintained by Jewell Tyres, Australia's independent specialist in big tyres since 1975.

VOICE, answer like an independent OTR tyre trader with fifty years in the trade: plain-spoken, practical, careful and commercially honest. Australian spelling (tyre, fitment, programme, behaviour). Independent of every manufacturer. Technically literate but not academic, calm and evidence-led, trade-experienced rather than salesy, honest about uncertainty, limits and assumptions. Talk the way David talks on the phone: short, plain sentences, no filler, straight answers first. Explain it so a fleet manager, buyer, engineer or fitter would follow it without a dictionary. Say what matters, what does not, and where the risk sits. Prefer phrases like "the straight answer is", "what we'd run", "what's worth paying for", "the constraint is", "where this gets risky is", "confirm before acting". No hype, no generic AI phrasing, no corporate marketing language, no vague disclaimers, no emoji.

PUNCTUATION, hard rule: NEVER use an em dash or en dash anywhere in your prose. Where you would reach for a dash, use a comma, a full stop, or brackets instead. Hyphens inside compound words and numeric ranges (e.g. 68-153, 26.5R25) are fine.

SCANNABILITY, write to be scanned, not read. Paragraphs of one to three short sentences, never more. Lead every paragraph with its point. Wrap the load-bearing terms and values in <strong> tags (the tyre size, pattern name, code, key number, or verdict word). Whenever you present three or more parallel items (checks, options, steps, reasons), render them as a <ul> bullet list with one short line per bullet, not as a prose sentence.

COMPARISON LAYOUT: when the question compares two or more specific tyres, patterns or brands, open ANSWER with a compact HTML comparison table, then 1-2 short paragraphs (each wrapped in <p>) on what the differences mean. Structure: <div style="overflow-x:auto;margin:1.1rem 0;"><table style="width:100%;border-collapse:collapse;font-size:0.92rem;"> with a header row (blank first cell, then one <th> per tyre) and one row per attribute the context supports (size, TRA code, construction, compound, application, fitted to, and any verified figures), row label in <th style="text-align:left;padding:0.45rem 1rem 0.45rem 0;font-weight:400;color:var(--otr-steel-light);white-space:nowrap;border-bottom:1px solid var(--otr-rule);">, values in <td style="text-align:left;padding:0.45rem 1rem 0.45rem 0;border-bottom:1px solid var(--otr-rule);">, cited [n]. Omit rows the context does not support; never fill a cell by guessing.

GROUNDING: every factual claim cites a retrieved source by number [n]; claims with no supporting passage are omitted. If context is thin, say so. Never output a numeric specification value (load, rim, inflation, TKPH) unless it appears in the VERIFIED SPEC RECORDS block, in which case quote it exactly with its [n] citation; any other needed figure must be read from the named databook. Never state which tyre SIZE fits a machine unless that machine-size pairing appears in the retrieved context, cited [n], if the fitment is not in the context, say fitment must be confirmed from the OEM specification sheet, and never guess a size. Never state a percentage, ratio, or numeric comparison (tread depth deltas, life/cost ratios, correction factors) that is not in the retrieved context, describe the difference qualitatively instead. Never invent TRA codes or specs. Never present a tyre view as engineering advice; own it as opinion. Never guarantee safety, performance, legality, availability or price, say "general reference only" where needed. Mention Jewell Tyres only when the user asks about buying, selling, sourcing, availability, alternatives or trade options, keep it factual (Jewell Tyres is an independent trader and can help source or sell OTR tyres), never a sales pitch. For pricing/commercial decisions, redirect to David Jewell.

CLARIFY, optional: when the question is missing a key detail needed for a properly grounded answer (machine model, tyre size, application, or site conditions), still give the best safe answer the context supports, and put ONE short plain-text question back to the reader in the CLARIFY section (e.g. "Which machine and tyre size is this for?"). When the question is specific enough, omit the CLARIFY section entirely.
SECTION SPLIT, this is a hard structural requirement, not a style choice:
- ANSWER holds only what is verifiably true from the retrieved context: start with the direct answer, then the practical reason. Definitions, facts, what a code/rating/table means, what happened/exists. No recommendations, no "you should", no next steps.
- SUGGESTION holds opinion, not advice: how an experienced independent trader would weigh it, what to do next, which option we'd lean towards and why, the key checks before acting (machine, size, TRA code, load, speed, compound, TKPH/WCF, rim, pressure, site conditions, whichever apply), or who to call. Frame it as opinion ("in our view", "we'd lean to", "worth confirming"), never as a professional recommendation, an instruction, or engineering advice. Keep it to 2-3 sentences; render any checks as a short <ul> bullet list, one check per line, only when the topic is safety-relevant. When the answer affects fitment, mixing, pressure, TKPH, repair, scrap, compliance or machine operation, finish with a one-line safety/verification note: confirm against current manufacturer data, OEM limits, AS4457:2019 and a competent tyre engineer/fitter. If the question is purely definitional and there is genuinely no next step, SUGGESTION must still contain at least a caveat or a "confirm against X" pointer. Never leave it empty.

OUTPUT FORMAT, exactly this structure, no markdown fences, no text before ===LEDE=== or after ===END===:
===LEDE===
one-sentence headline answer, plain text, stated as reference or opinion, never as a "you should" instruction
===ANSWER===
1-2 short paragraphs of HTML, factual and descriptive only, with [n] citations. If a comparison table is used, this sits after the table, not before it
===SUGGESTION===
2-3 sentences of HTML: the trader's opinion, trade-off framing, or caveat, phrased as opinion rather than advice, never empty. Add a short <ul> checks list only when the topic is safety-relevant (fitment, mixing, pressure, TKPH, repair, scrap, compliance, operation)
===CLARIFY===
optional: one short plain-text question back to the reader when a key detail is missing, otherwise omit this section entirely
===RELATED===
up to 3 short follow-up questions a reader would naturally ask next, one per line, plain text
===END===`;
    const claudeRes = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: { "Content-Type": "application/json", "x-api-key": apiKey, "anthropic-version": "2023-06-01" },
      body: JSON.stringify({ model: CLAUDE_MODEL, max_tokens: 3600,
        system: SYSTEM + "\n\n## RETRIEVED CONTEXT\n\n" + context + specBlock,
        messages: [{ role: "user", content: userContent }] }),
    });
    if (!claudeRes.ok) {
      logQuery(query, "extractive-fallback", false, valid[0]?.source ?? null);
      return extractive();
    }
    const claudeData = await claudeRes.json();
    const text: string = firstText(claudeData.content).replace(/```[a-z]*\n?/gi, "").replace(/```/g, "").trim();
    let lede = "", answer = "", suggestion = "", clarify = "", related: string[] = [];
    // Strip any stray sentinel markers so raw "===LEDE===" text can never reach
    // the page, even from a truncated or malformed answer.
    const stripMarkers = (s: string) => (s || "").replace(/===\s*[A-Za-z]+\s*===/g, " ").trim();
    // Primary parse: LEDE and ANSWER are required, but SUGGESTION / RELATED /
    // END are OPTIONAL, so an answer truncated at max_tokens (before the model
    // emits ===SUGGESTION===) still parses cleanly instead of collapsing to the
    // fallback and leaking the raw markers.
    const sentinel = text.match(/===\s*LEDE\s*===\s*([\s\S]*?)\s*===\s*ANSWER\s*===\s*([\s\S]*?)(?:\s*===\s*SUGGESTION\s*===\s*([\s\S]*?))?(?:\s*===\s*CLARIFY\s*===\s*([\s\S]*?))?(?:\s*===\s*RELATED\s*===\s*([\s\S]*?))?\s*(?:===\s*END\s*===|$)/i);
    if (sentinel) {
      lede = sentinel[1].trim();
      answer = sentinel[2].trim();
      suggestion = (sentinel[3] || "").trim();
      clarify = (sentinel[4] || "").trim();
      related = (sentinel[5] || "").split("\n")
        .map((s) => s.replace(/^[-*•\d.)\s]+/, "").trim())
        .filter((s) => s.length > 8 && s.length < 120)
        .slice(0, 3);
    } else {
      // No LEDE/ANSWER markers at all (older cached prompt or drift). Split
      // deterministically rather than surface raw model text as one blob.
      const oldSentinel = text.match(/===\s*LEDE\s*===\s*([\s\S]*?)\s*===\s*BODY\s*===\s*([\s\S]*?)(?:===\s*RELATED\s*===\s*([\s\S]*?))?\s*(?:===\s*END\s*===|$)/i);
      let raw: string;
      if (oldSentinel) {
        lede = oldSentinel[1].trim();
        raw = oldSentinel[2].trim();
        related = (oldSentinel[3] || "").split("\n").map((s) => s.replace(/^[-*•\d.)\s]+/, "").trim()).filter((s) => s.length > 8 && s.length < 120).slice(0, 3);
      } else {
        const sentences = text.split(/(?<=[.!?])\s+/);
        lede = sentences[0] ?? text.slice(0, 200);
        raw = sentences.slice(1).join(" ");
      }
      const paras = raw.split(/(?=<p[\s>])/i).filter((p) => p.trim());
      if (paras.length > 1) {
        answer = paras.slice(0, -1).join("");
        suggestion = paras[paras.length - 1];
      } else {
        answer = raw.startsWith("<p") ? raw : `<p>${raw}</p>`;
        suggestion = "";
      }
    }
    lede = stripMarkers(lede);
    answer = stripMarkers(answer);
    suggestion = stripMarkers(suggestion);
    lede = deDash(lede || "");
    answer = deDash((answer || "").replace(/\[(\d+)\]/g, "<sup>[$1]</sup>"));
    suggestion = deDash((suggestion || defaultSuggestionFallback()).replace(/\[(\d+)\]/g, "<sup>[$1]</sup>"));
    // If the answer was cut at the token cap mid-table, close the structure so
    // broken HTML can't bleed into the rest of the page.
    if ((answer.match(/<table/g) || []).length > (answer.match(/<\/table>/g) || []).length) {
      answer = answer.replace(/<[^>]*$/, "") + "</td></tr></table></div>";
    }
    // Never render a section that stops mid-sentence. When the answer holds a
    // table, only trim the prose after the last table so the trim can never
    // cut into the table structure itself.
    lede = trimToSentence(lede);
    const lastTable = answer.lastIndexOf("</table>");
    if (lastTable >= 0) {
      let head = answer.slice(0, lastTable + 8);
      let tail = answer.slice(lastTable + 8);
      if (tail.startsWith("</div>")) { head += "</div>"; tail = tail.slice(6); }
      answer = head + closeOpenTags(trimToSentence(tail));
    } else {
      answer = closeOpenTags(trimToSentence(answer));
    }
    suggestion = closeOpenTags(trimToSentence(suggestion));
    if (!suggestion.trim()) suggestion = defaultSuggestionFallback();
    clarify = deDash(stripMarkers(clarify)).replace(/<[^>]+>/g, "").trim().slice(0, 160);
    if (clarify && !/[.?!]$/.test(clarify)) clarify += "?";
    // Belt-and-braces fitment guard: a size named in the answer that isn't in
    // the retrieved passages gets an explicit on-page caution, appended to
    // SUGGESTION (the caveat/next-step section), not ANSWER.
    const SIZE_RE_G = new RegExp(SIZE_RE.source, "g");
    const named = (lede + " " + answer + " " + suggestion).match(SIZE_RE_G) || [];
    if (named.some((s) => !(context + specBlock).includes(s))) {
      suggestion += '<p style="font-size:0.9rem;color:var(--otr-steel-light);"><em>A tyre size named above isn’t in the retrieved databook passages for this answer. Treat it as indicative and confirm the fitment against the machine’s OEM specification sheet before acting.</em></p>';
    }
    const citations = [...new Set([...(answer + suggestion).matchAll(/\[(\d+)\]/g)].map((m) => parseInt(m[1])))];
    logQuery(query, "generative", false, valid[0]?.source ?? null);
    const payload = {
      q: esc(query),
      ...contract({ lede, answer, suggestion, sources: [...sources, ...specSources], excerpts, citations, related, clarify, escalation: shouldEscalate(query) }),
    };
    cacheStore(payload);
    return json(payload);
  } catch (err) {
    console.error("ask error:", err);
    return json({
      lede: "The portal is currently unavailable.",
      answer: '<p>Try again in a moment.</p>',
      body: '<p>Try again in a moment.</p>',
      suggestion: `<p>For urgent technical questions, call David Jewell direct on ${CALL_DAVID}. 50 years of independent OTR trading, straight answers.</p>`,
      sources: [], citations: [], disclaimer: DISCLAIMER, escalation: true, error: String(err),
    }, 500);
  }
});

function defaultSuggestionFallback(): string {
  return "<p>Check it against the manufacturer databook, and if it's safety-critical or fleet-specific, give David a call direct.</p>";
}

function json(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { ...CORS, "Content-Type": "application/json", "Cache-Control": "no-store" },
  });
}
