// Builds the Cloudflare Pages project from the same modules the worker uses,
// so the Pages deploy and the worker never drift apart.
import { summaryPage } from './summary.js';
import { packPage } from './sheets.js';
import { gatePage } from './worker.js';
import fs from 'node:fs';
import path from 'node:path';

const root = path.dirname(new URL(import.meta.url).pathname);
const pub = path.join(root, 'pages/public');
const fns = path.join(root, 'pages/functions');
fs.mkdirSync(pub, { recursive: true });
fs.mkdirSync(fns, { recursive: true });

fs.writeFileSync(path.join(pub, 'index.html'), summaryPage());
fs.writeFileSync(path.join(pub, 'pack.html'), packPage());

// Private pack: never indexed, never cached.
fs.writeFileSync(path.join(pub, '_headers'), `/*
  X-Robots-Tag: noindex, nofollow, noarchive, nosnippet
  X-Content-Type-Options: nosniff
  Referrer-Policy: no-referrer
  Cache-Control: no-store
`);

// The gate is rendered at build time into two static shells; the middleware
// only chooses between them, so no page markup lives in the function.
const gateOk = gatePage('__NEXT__', false);
const gateErr = gatePage('__NEXT__', true);

const middleware = `// Password gate for the 3D Process pack. Generated by build-pages.mjs.
const DEFAULT_PASSWORD = 'otr2026';
const COOKIE_NAME = 'otr3d';
const GATE_OK = ${JSON.stringify(gateOk)};
const GATE_ERR = ${JSON.stringify(gateErr)};

const SECURITY = {
  'x-robots-tag': 'noindex, nofollow, noarchive, nosnippet',
  'x-content-type-options': 'nosniff',
  'cache-control': 'no-store',
  'referrer-policy': 'no-referrer',
};

async function tokenFor(password) {
  const data = new TextEncoder().encode('otr-3d-process:' + password);
  const digest = await crypto.subtle.digest('SHA-256', data);
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

function readCookie(request, name) {
  const header = request.headers.get('cookie') || '';
  for (const part of header.split(';')) {
    const [k, ...rest] = part.trim().split('=');
    if (k === name) return rest.join('=');
  }
  return null;
}

function gate(next, failed) {
  const safe = String(next).replace(/"/g, '&quot;');
  const body = (failed ? GATE_ERR : GATE_OK).split('__NEXT__').join(safe);
  return new Response(body, {
    status: 401,
    headers: { 'content-type': 'text/html; charset=UTF-8', ...SECURITY },
  });
}

export async function onRequest(context) {
  const { request, env, next } = context;
  const url = new URL(request.url);
  const password = env.SITE_PASSWORD || DEFAULT_PASSWORD;
  const expected = await tokenFor(password);

  if (url.pathname === '/__auth') {
    if (request.method !== 'POST') {
      return new Response('Method Not Allowed', { status: 405, headers: SECURITY });
    }
    const form = await request.formData();
    const supplied = String(form.get('password') || '');
    let dest = String(form.get('next') || '/');
    if (!dest.startsWith('/') || dest.startsWith('//')) dest = '/';
    if (supplied !== password) return gate(dest, true);
    return new Response(null, {
      status: 303,
      headers: {
        location: dest,
        'set-cookie': COOKIE_NAME + '=' + expected + '; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000',
        ...SECURITY,
      },
    });
  }

  if (readCookie(request, COOKIE_NAME) !== expected) {
    return gate(url.pathname + url.search, false);
  }

  const res = await next();
  const out = new Response(res.body, res);
  for (const [k, v] of Object.entries(SECURITY)) out.headers.set(k, v);
  return out;
}
`;
fs.writeFileSync(path.join(fns, '_middleware.js'), middleware);

const kb = (p) => (fs.statSync(p).size / 1024).toFixed(0) + 'KB';
console.log('public/index.html      ', kb(path.join(pub, 'index.html')));
console.log('public/pack.html       ', kb(path.join(pub, 'pack.html')));
console.log('functions/_middleware.js', kb(path.join(fns, '_middleware.js')));
